# Generated by Django 4.2.5 on 2023-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('specialty', models.CharField(max_length=60)),
                ('images', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
