# Generated by Django 4.2.5 on 2023-09-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='specialty',
            new_name='muttaxasisligi',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='images',
            new_name='rasmi',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='full_name',
            new_name='toliq_name',
        ),
    ]
